Declare Sub TITLE ()
Declare Sub TITLE_CAREER ()
Declare Sub TITLE_EDITSTATS ()
Declare Sub TITLE_HEADER ()
Declare Sub TITLE_LEADERS
Declare Sub TITLE_MERGE ()
Declare Sub TITLE_SCHEDULER ()
Declare Sub TITLE_STATS ()
Declare Sub TITLE_STAT_HEADER (header$)
Declare Sub TITLE_TOURN ()
Declare Sub TITLE_UTILS ()
